Convert to extension handler
sensu-plugins/sensu-extensions-opsgenie pull request #1
Opened 2017-06-02 03:30 UTC by agoddard

2017-06-02 03:36 UTC, majormoses requested changes

2017-06-02 03:36 UTC, majormoses commented on .github/PULL_REQUEST_TEMPLATE.md
> +#### New Plugins
We can kill this section no?

2017-06-02 03:36 UTC, majormoses commented on .travis.yml
> +- gem build sensu-plugins-opsgenie.gemspec
extensions

2017-06-02 03:36 UTC, majormoses commented on .travis.yml
> +- gem install sensu-plugins-opsgenie-*.gem
extensions

2017-06-02 03:36 UTC, majormoses commented on .travis.yml
> +    secure: K0vq7Ahny7bZIz1LnilosmNgHG/L4Nv6QuPaxo++/lQ7dWT9puRDLFw/pQI7+Xgb+LBLWFW2ye33q01qd1Cke8nuMKQduxnGeBzzH6fHJiXDcz5uEoKB2a8qdkwHHP3y9fisGaZgyhxlmui3fny3C0JjFizs9oNNYIt3MZcETTk=
will need someone with rubygems access to generate and populate.

2017-06-02 03:36 UTC, majormoses commented on .travis.yml
> +  gem: sensu-plugins-opsgenie
extensions

2017-06-02 03:36 UTC, majormoses commented on .travis.yml
> +    repo: sensu-plugins/sensu-plugins-opsgenie
extensions

2017-06-02 03:36 UTC, majormoses commented on Rakefile
> +  args = if RUBY_VERSION >= '2.0.0'
we don't support ruby > 2 so we can clean this up.

2017-06-02 03:36 UTC, majormoses commented on Rakefile
> +  bin_list = Gem::Specification.load('sensu-plugins-opsgenie.gemspec').executables
extensions

2017-07-31 08:39 UTC, luisdavim commented
Hi @agoddard can you please give some Feedback on @majormoses's comments?
Thanks.

2018-01-08 23:03 UTC, mbbroberg commented
Hey @luisdavim, given this branch is on the repo, would you be okay with resolving this list of changes?

2018-02-09 04:01 UTC, majormoses commented
As there is a lack of response/traction I'd say we should probably close this out or someone claim it. If no one claims this within the next week we should close the PR and create an issue for someone to claim in the future.

2018-04-08 00:13 UTC, majormoses commented
closing due to lack of activity

2018-04-08 00:13 UTC, closed without merging